.class public final Lcom/google/protos/dots/DotsShared;
.super Ljava/lang/Object;
.source "DotsShared.java"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/google/protos/dots/DotsShared$1;,
        Lcom/google/protos/dots/DotsShared$PostReadState;,
        Lcom/google/protos/dots/DotsShared$PostReadStateOrBuilder;,
        Lcom/google/protos/dots/DotsShared$RoleList;,
        Lcom/google/protos/dots/DotsShared$RoleListOrBuilder;,
        Lcom/google/protos/dots/DotsShared$SectionBlacklist;,
        Lcom/google/protos/dots/DotsShared$SectionBlacklistOrBuilder;,
        Lcom/google/protos/dots/DotsShared$ClientTime;,
        Lcom/google/protos/dots/DotsShared$ClientTimeOrBuilder;,
        Lcom/google/protos/dots/DotsShared$ClientSavedPostsState;,
        Lcom/google/protos/dots/DotsShared$ClientSavedPostsStateOrBuilder;,
        Lcom/google/protos/dots/DotsShared$SavedPost;,
        Lcom/google/protos/dots/DotsShared$SavedPostOrBuilder;,
        Lcom/google/protos/dots/DotsShared$LiveContent;,
        Lcom/google/protos/dots/DotsShared$LiveContentOrBuilder;,
        Lcom/google/protos/dots/DotsShared$C2dmMessage;,
        Lcom/google/protos/dots/DotsShared$C2dmMessageOrBuilder;,
        Lcom/google/protos/dots/DotsShared$ClientEntity;,
        Lcom/google/protos/dots/DotsShared$ClientEntityOrBuilder;,
        Lcom/google/protos/dots/DotsShared$EntityId;,
        Lcom/google/protos/dots/DotsShared$EntityIdOrBuilder;,
        Lcom/google/protos/dots/DotsShared$UserWhen;,
        Lcom/google/protos/dots/DotsShared$UserWhenOrBuilder;,
        Lcom/google/protos/dots/DotsShared$SyncHandshake;,
        Lcom/google/protos/dots/DotsShared$SyncHandshakeOrBuilder;,
        Lcom/google/protos/dots/DotsShared$SyncFile;,
        Lcom/google/protos/dots/DotsShared$SyncFileOrBuilder;,
        Lcom/google/protos/dots/DotsShared$EntitySubscriptionInfo;,
        Lcom/google/protos/dots/DotsShared$EntitySubscriptionInfoOrBuilder;,
        Lcom/google/protos/dots/DotsShared$Section;,
        Lcom/google/protos/dots/DotsShared$SectionOrBuilder;,
        Lcom/google/protos/dots/DotsShared$Role;,
        Lcom/google/protos/dots/DotsShared$RoleOrBuilder;,
        Lcom/google/protos/dots/DotsShared$PostSummaryResults;,
        Lcom/google/protos/dots/DotsShared$PostSummaryResultsOrBuilder;,
        Lcom/google/protos/dots/DotsShared$PostSummaryResult;,
        Lcom/google/protos/dots/DotsShared$PostSummaryResultOrBuilder;,
        Lcom/google/protos/dots/DotsShared$PostSummary;,
        Lcom/google/protos/dots/DotsShared$PostSummaryOrBuilder;,
        Lcom/google/protos/dots/DotsShared$PostResult;,
        Lcom/google/protos/dots/DotsShared$PostResultOrBuilder;,
        Lcom/google/protos/dots/DotsShared$PostPreviewContext;,
        Lcom/google/protos/dots/DotsShared$PostPreviewContextOrBuilder;,
        Lcom/google/protos/dots/DotsShared$ArticleFeatures;,
        Lcom/google/protos/dots/DotsShared$ArticleFeaturesOrBuilder;,
        Lcom/google/protos/dots/DotsShared$Post;,
        Lcom/google/protos/dots/DotsShared$PostOrBuilder;,
        Lcom/google/protos/dots/DotsShared$ObjectIdProto;,
        Lcom/google/protos/dots/DotsShared$ObjectIdProtoOrBuilder;,
        Lcom/google/protos/dots/DotsShared$Library;,
        Lcom/google/protos/dots/DotsShared$LibraryOrBuilder;,
        Lcom/google/protos/dots/DotsShared$Item;,
        Lcom/google/protos/dots/DotsShared$ItemOrBuilder;,
        Lcom/google/protos/dots/DotsShared$Form;,
        Lcom/google/protos/dots/DotsShared$FormOrBuilder;,
        Lcom/google/protos/dots/DotsShared$DisplayTemplate;,
        Lcom/google/protos/dots/DotsShared$DisplayTemplateOrBuilder;,
        Lcom/google/protos/dots/DotsShared$DisplayTarget;,
        Lcom/google/protos/dots/DotsShared$DisplayTargetOrBuilder;,
        Lcom/google/protos/dots/DotsShared$DataSource;,
        Lcom/google/protos/dots/DotsShared$DataSourceOrBuilder;,
        Lcom/google/protos/dots/DotsShared$AppFamilySummary;,
        Lcom/google/protos/dots/DotsShared$AppFamilySummaryOrBuilder;,
        Lcom/google/protos/dots/DotsShared$ApplicationSummaryResults;,
        Lcom/google/protos/dots/DotsShared$ApplicationSummaryResultsOrBuilder;,
        Lcom/google/protos/dots/DotsShared$ApplicationSummaryResult;,
        Lcom/google/protos/dots/DotsShared$ApplicationSummaryResultOrBuilder;,
        Lcom/google/protos/dots/DotsShared$ApplicationSummary;,
        Lcom/google/protos/dots/DotsShared$ApplicationSummaryOrBuilder;,
        Lcom/google/protos/dots/DotsShared$ApplicationDesign;,
        Lcom/google/protos/dots/DotsShared$ApplicationDesignOrBuilder;,
        Lcom/google/protos/dots/DotsShared$Application;,
        Lcom/google/protos/dots/DotsShared$ApplicationOrBuilder;,
        Lcom/google/protos/dots/DotsShared$ReadingPosition;,
        Lcom/google/protos/dots/DotsShared$ReadingPositionOrBuilder;,
        Lcom/google/protos/dots/DotsShared$AnalyticsEvent;,
        Lcom/google/protos/dots/DotsShared$AnalyticsEventOrBuilder;,
        Lcom/google/protos/dots/DotsShared$StoreType;,
        Lcom/google/protos/dots/DotsShared$EditionApproval;,
        Lcom/google/protos/dots/DotsShared$TocSplashType;,
        Lcom/google/protos/dots/DotsShared$DataCollectionChoice;,
        Lcom/google/protos/dots/DotsShared$FeatureFlag;,
        Lcom/google/protos/dots/DotsShared$Device;,
        Lcom/google/protos/dots/DotsShared$IssueType;,
        Lcom/google/protos/dots/DotsShared$DataCollectionPolicy;,
        Lcom/google/protos/dots/DotsShared$Category;
    }
.end annotation
